#---------BASE IMAGE---------

FROM   ubuntu:20.04

#---------LABELS---------

LABEL        maintainer="Aditya Kale adityakale732@gmail.com"
LABEL        image="sample_app:1.0"
LABEL        version="1.0"
LABEL        description="Dockerfile for sample python web app"


#---------COPY FOLDERS---------

COPY   /python_project /var/www/FLASKAPPS/webapp/
COPY   /requirement.txt   /tmp

#---------APP DEPENDENCIES---------

RUN    apt-get clean && apt-get update -y
RUN    apt-get install python3 -y && ln -s /usr/bin/python3 /usr/bin/python
RUN    apt-get install apache2 libapache2-mod-wsgi-py3  -y
RUN    apt-get update && apt-get install python3-pip libpq-dev -y
# Installing python dependencies
RUN    pip3 install --no-cache-dir -r /tmp/requirement.txt 


# Configure Apache
COPY apache-config.conf /etc/apache2/sites-available/000-default.conf
 
# Enable required Apache modules
RUN a2enmod rewrite
RUN a2enmod headers


#---------CMD OR ENTRYPOINT---------

# Start Apache in the foreground when the container starts
CMD ["apache2ctl", "-D", "FOREGROUND"]

#---------PORTS---------

# Expose port 80 for incoming web traffic
EXPOSE 80

# docker build --tag sample_app:1.0 -f Dockerfile .